import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>ciao</h1>
        <Link href="/sessions/1">Session 1</Link>
        <Link href="/sessions/2">Session 2</Link>
      </main>
    </div>
  );
};

export default Home;
