version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: notSoCoolPassword
      POSTGRES_USER: postgres
      POSTGRES_DB: PickAMovie
    expose: 
      - 5432
    ports: 
      - "5432:5432"
  backend:
    build: ./backend
    networks: 
      - default
    depends_on:
      - db
    ports: 
      - "1337:1337"