/* tslint:disable */
/* eslint-disable */
/**
 * PickAMovie Swagger API
 * May the force be with us
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCreateProposalRequest
 */
export interface ModelsCreateProposalRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateProposalRequest
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateProposalRequest
     */
    movieId: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateProposalRequest
     */
    sessionId: number;
}

export function ModelsCreateProposalRequestFromJSON(json: any): ModelsCreateProposalRequest {
    return ModelsCreateProposalRequestFromJSONTyped(json, false);
}

export function ModelsCreateProposalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCreateProposalRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'movieId': json['movieId'],
        'sessionId': json['sessionId'],
    };
}

export function ModelsCreateProposalRequestToJSON(value?: ModelsCreateProposalRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'movieId': value.movieId,
        'sessionId': value.sessionId,
    };
}


