/* tslint:disable */
/* eslint-disable */
/**
 * PickAMovie Swagger API
 * May the force be with us
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsVote
 */
export interface ModelsVote {
    /**
     * 
     * @type {string}
     * @memberof ModelsVote
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsVote
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsVote
     */
    proposalId: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsVote
     */
    updatedAt?: string;
}

export function ModelsVoteFromJSON(json: any): ModelsVote {
    return ModelsVoteFromJSONTyped(json, false);
}

export function ModelsVoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsVote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'id': json['id'],
        'proposalId': json['proposalId'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function ModelsVoteToJSON(value?: ModelsVote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'id': value.id,
        'proposalId': value.proposalId,
        'updatedAt': value.updatedAt,
    };
}


