/* tslint:disable */
/* eslint-disable */
/**
 * PickAMovie Swagger API
 * May the force be with us
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCreateVoteRequest
 */
export interface ModelsCreateVoteRequest {
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateVoteRequest
     */
    id: number;
}

export function ModelsCreateVoteRequestFromJSON(json: any): ModelsCreateVoteRequest {
    return ModelsCreateVoteRequestFromJSONTyped(json, false);
}

export function ModelsCreateVoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCreateVoteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ModelsCreateVoteRequestToJSON(value?: ModelsCreateVoteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


