/* tslint:disable */
/* eslint-disable */
/**
 * PickAMovie Swagger API
 * May the force be with us
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCreateSessionRequest
 */
export interface ModelsCreateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateSessionRequest
     */
    endAt: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateSessionRequest
     */
    startAt: string;
}

export function ModelsCreateSessionRequestFromJSON(json: any): ModelsCreateSessionRequest {
    return ModelsCreateSessionRequestFromJSONTyped(json, false);
}

export function ModelsCreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCreateSessionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endAt': json['endAt'],
        'startAt': json['startAt'],
    };
}

export function ModelsCreateSessionRequestToJSON(value?: ModelsCreateSessionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'endAt': value.endAt,
        'startAt': value.startAt,
    };
}


